#!/usr/bin/env ruby

require 'yaml'
require 'resolv'
['lib', 'lib/pingman'].each do |dir|
  Dir[File.expand_path("../#{dir}", __FILE__) << '/*.rb'].each do |file|
    require file
  end
end

Signal.trap(:INT){
  exit 0
}

config = ARGV.size > 0 ? YAML.load_file(File.expand_path(ARGV[0])) :
  YAML.load_file(File.expand_path('../sample.yml', __FILE__))

resolv = Resolv::DNS.new
lines = []
config.each do |k, v|
  line = Line.new
  line.hostname = v['name'] || v['host']
  begin
    line.address = resolv.getresource(v['host'], Resolv::DNS::Resource::IN::A).address.to_s
  rescue
    line.address = v['host']
  end
  line.row = lines.size
  lines.push line
end

Pingman.pingman lines
